imports:
    - { resource: child_services.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Nordeus\CrowdUserBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Curl\Curl: ~

    Nordeus\CrowdUserBundle\CrowdService\CrowdService:
        arguments:
            $appName: "%nordeus_crowd_user.crowd_application_name%"
            $appPassword: "%nordeus_crowd_user.crowd_application_password%"
            $serviceUrl: "%nordeus_crowd_user.crowd_service_url%"
            $baseUri: "%nordeus_crowd_user.service_uri%"
            $curlTimeout: "%nordeus_crowd_user.curl_timeout%"
            $crowdConnectionFailureRetries: "%nordeus_crowd_user.connection_retries%"

    crowd.user_provider:
        class: Nordeus\CrowdUserBundle\Security\User\UserProvider
        arguments:
            $rolesToCrowdGroupsMap: "%nordeus_crowd_user.roles_to_groups%"
            $userRefreshTime: "%nordeus_crowd_user.user_refresh_time%"
            $userClass: "%nordeus_crowd_user.user_class%"

    crowd.security.authentication.provider:
        class: Nordeus\CrowdUserBundle\Security\Authentication\CrowdAuthenticationProvider
        arguments:
            $userProvider: ~

    crowd.security.authentication.listener.sso:
        class: Nordeus\CrowdUserBundle\Security\Authentication\CrowdSSOAuthenticationListener
        arguments:
            $ssoCookieName: "%nordeus_crowd_user.sso_cookie_name%"
            $ssoCookieDomain: "%nordeus_crowd_user.sso_cookie_domain%"

    crowd.security.authentication.listener.sso_response:
        class: Nordeus\CrowdUserBundle\Security\Authentication\CrowdResponseListener
        tags:
            - { name: kernel.event_listener, event: kernel.response }

    crowd.security.authentication.success_handler.login:
        class: Nordeus\CrowdUserBundle\Security\Authentication\CrowdLoginSuccessHandler
        arguments:
            $options: []
            $ssoCookieName: "%nordeus_crowd_user.sso_cookie_name%"
            $ssoCookieDomain: "%nordeus_crowd_user.sso_cookie_domain%"

    crowd.security.logout.handler.sso:
        class: Nordeus\CrowdUserBundle\Security\Authentication\CrowdSSOLogoutHandler
        arguments:
            $ssoCookieName: "%nordeus_crowd_user.sso_cookie_name%"
            $ssoCookieDomain: "%nordeus_crowd_user.sso_cookie_domain%"

    crowd.access_denied_handler:
        class: Nordeus\CrowdUserBundle\Util\AccessDeniedHandler

    crowd.rest.access_denied_handler:
        class: Nordeus\CrowdUserBundle\Util\Rest\AccessDeniedHandler

    crowd.rest.unauthorized_entry_point_handler:
        class: Nordeus\CrowdUserBundle\Util\Rest\UnauthorizedEntryPointHandler

    crowd.rest.login_failure_handler:
        class: Nordeus\CrowdUserBundle\Util\Rest\LoginFailureHandler

    crowd.rest.logout_success_handler:
        class: Nordeus\CrowdUserBundle\Util\Rest\LogoutSuccessHandler
